#!/usr/bin/env node
// Generate edge ruleset JSON files from edge-policy.mjs
// Usage: npm run edge:ruleset [-- --dry-run]
//
// IMPORTANT: This script does NOT call cf CLI. It only generates JSON files + prints cf commands.
//            You must manually review and run the printed cf commands to apply changes.
//            BEFORE RUNNING cf update:
//              1. `cf rulesets account-rulesets phases get <phase> -z <zone-id>` to snapshot current config
//              2. That snapshot is your rollback point.

import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { buildRedirectRules, buildCacheRules, buildFirewallRules } from '../src/lib/edge-policy.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = join(__dirname, '..');

const OUTPUT_DIR = join(root, '.edge-ruleset');

// Phase mapping: folder/filename friendly name -> actual Cloudflare phase name
const PHASES = {
  redirect: 'http_request_dynamic_redirect',
  cache: 'http_request_cache_settings',
  firewall: 'http_request_firewall_custom',
  ratelimit: 'http_ratelimit', // not generated by this module
};

function main() {
  const dryRun = process.argv.includes('--dry-run');
  const zoneId = process.env.CF_ZONE_ID || '<zone-id>';

  // Check for missing zone-id
  if (!process.env.CF_ZONE_ID) {
    console.warn(`WARNING: CF_ZONE_ID not set. Using placeholder <zone-id>.`);
    console.warn(`         Run \`cf zones list\` to look up your zone ID.`);
    console.warn(``);
  }

  const phasesData = {
    redirect: buildRedirectRules(),
    cache: buildCacheRules(),
    firewall: buildFirewallRules(),
  };

  if (!dryRun) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  for (const [key, rules] of Object.entries(phasesData)) {
    const phase = PHASES[key];
    const filename = `${phase}.json`;
    const filepath = join(OUTPUT_DIR, filename);
    const json = JSON.stringify(rules, null, 2);
    
    if (dryRun) {
      console.log(`[DRY-RUN] Would write ${filepath} (${rules.length} rules)`);
    } else {
      fs.writeFileSync(filepath, json, 'utf8');
      console.log(`Wrote ${filepath} (${rules.length} rules)`);
    }

    // Print cf command
    const cmdValidate = `cf rulesets account-rulesets phases update ${phase} -z ${zoneId} --rules @${filepath} --validate-only`;
    const cmdApply = `cf rulesets account-rulesets phases update ${phase} -z ${zoneId} --rules @${filepath}`;

    console.log(`  cf command (validate): ${cmdValidate}`);
    console.log(`  cf command (apply):    ${cmdApply}`);
    console.log(`  # NOTE: update replaces the entire phase rule list!`);
    console.log(`  # First, do: cf rulesets account-rulesets phases get ${phase} -z ${zoneId}`);
    console.log(`  # That snapshot is your rollback point.`);
    if (key === 'ratelimit') {
      console.log(`  # SKIPPED: http_ratelimit is not generated by this module.`);
    }
    console.log('');
  }

  console.log(`Summary: ${phasesData.redirect.length} redirect, ${phasesData.cache.length} cache, ${phasesData.firewall.length} firewall rules written.`);
}

try {
  main();
} catch (err) {
  console.error('Error:', err.message);
  process.exit(1);
}
